FROM alpine

RUN apk update
RUN apk add make go git gcc libc-dev && rm -rf /var/cache/apk/*

ENV GOPATH /go
ENV PLUGINDIR /go/src/github.com/anusha-ragunathan/global-net-plugin

RUN mkdir -p /go/run/docker/plugins

COPY . ${PLUGINDIR}
WORKDIR ${PLUGINDIR}
RUN go install --ldflags '-extldflags "-static"'

WORKDIR /go

RUN rm -rf /go/pkg
RUN rm -rf /go/src

BUILD /go
FROM scratch
ADD run /run
ADD bin /bin
CMD [/bin/test-docker-netplugin]
